# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57a5a625ed9b191b36b77ab8c2238038a356ae73a65c3bbd8a6a49473325d1b93b00c41a7c3614d8c685163d894fa39babe2ccbbfc0aaa71dc3e03a2b5f48e7f

test:
  secret_key_base: 5fc10fd22769549280de3ef7e2bedca348da666527ab1bc7c5444585809498322bbca3aeae1ad58627b1ece0fb0593993111c8a7ac7cdb8fc8770c534b459c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
